---
title: "Taller R - Rifa Valentina"
subtitle: "3. Visualización de datos con ggplot2"
date: "`02/02/2022`"
output:
  xaringan::moon_reader:
    lib_dir: libs
    css: [xaringan-themer.css]
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---


```{r setup, include=FALSE}
options(htmltools.dir.version = FALSE)
```

```{r xaringan-themer, include=FALSE, warning=FALSE}
library(xaringanthemer)
library(dplyr)
library(guaguas)

dark_yellow <- "#9667db"
light_yellow <- "#F7E9FD"
gray <- "#333333"
blue <- "#4466B0"

style_duo(
  # colors
  primary_color = light_yellow,
  secondary_color = dark_yellow,
  header_color = gray,
  text_color = gray,
  code_inline_color = colorspace::lighten(gray),
  text_bold_color = colorspace::lighten(gray),
  link_color = blue,
  title_slide_text_color = blue,

  # fonts
  header_font_google = google_font("Martel", "300", "400"),
  text_font_google = google_font("Lato"),
  code_font_google = google_font("Fira Mono")
)
```

```{r echo=FALSE,include=FALSE}
#pagedown::chrome_print(input="1.-trasponer.html",output="pdf/1. trasponer.pdf")
```

---

# Contenidos

+ Manipulación avanzada de data frames (funciones `pivot` y combinación de data frames)

+ Manipulación de fechas: paquete `lubridate`

+ **Visualización de datos con `ggplot2`**

+ Estimar desde diseños muestrales complejos (paquete `survey` y `srvyr`)

+ Hacer funciones, procesos iterativos e introducción a paquetes en R


---

# Introducción



---

### Recursos utilizados

[Ilustraciones de Allison Horst](https://github.com/allisonhorst/stats-illustrations)

[Capacitación INE variables de tiempo en R](https://capacitacion-r-basico.github.io/sesion_4/#106)


