---
title: "Taller R - Rifa Valentina"
subtitle: "5. Hacer funciones y procesos iterativos"
date: "`16/02/2022`"
output:
  xaringan::moon_reader:
    lib_dir: libs
    css: [xaringan-themer.css]
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---


```{r setup, include=FALSE}
options(htmltools.dir.version = FALSE)
```

```{r xaringan-themer, include=FALSE, warning=FALSE}
library(xaringanthemer)
library(dplyr)
library(guaguas)

dark_yellow <- "#9667db"
light_yellow <- "#F7E9FD"
gray <- "#333333"
blue <- "#4466B0"

style_duo(
  # colors
  primary_color = light_yellow,
  secondary_color = dark_yellow,
  header_color = gray,
  text_color = gray,
  code_inline_color = colorspace::lighten(gray),
  text_bold_color = colorspace::lighten(gray),
  link_color = blue,
  title_slide_text_color = blue,

  # fonts
  header_font_google = google_font("Martel", "300", "400"),
  text_font_google = google_font("Lato"),
  code_font_google = google_font("Fira Mono")
)
```

```{r echo=FALSE,include=FALSE}
#library(pagedown)
#pagedown::chrome_print("clase8c_agrupar_trasponer.html")

```



---

class: inverse, center, middle

# Proceso iterativo y condiciones

`for() e if()`

---

# Introducción

---

class: inverse, center, middle

# Funciones

`function()`


---

class: inverse, center, middle

# Entender los paquetes

`devtools`



---

### Recursos web utilizados

[Xaringan: Presentation Ninja, de Yihui Xie](https://github.com/yihui/xaringan). Para generar esta presentación.

[Ilustraciones de Allison Horst](https://github.com/allisonhorst/stats-illustrations)

### Para reforzar y seguir aprendiendo

[Video "el juego de las estadísticas"](https://www.youtube.com/watch?v=V8lbiiTF2P0) (utiliza gapminder)



